version: '2.4'
services:
  jwc_database:
    container_name: jwc_database
    image: mcr.microsoft.com/mssql/server:2019-latest
    restart: on-failure

    environment:
      SA_PASSWORD: ${MSSQL_PASSWORD:-password_!23}
      ACCEPT_EULA: y
      MSSQL_TCP_PORT: 1433
    ports:
      - "1433:1433"
    networks:
      - jwc
    volumes:
      - jwc_mssql_data:/var/opt/mssql

  jwc_database-test:
    container_name: jwc_database-test
    image: mcr.microsoft.com/mssql/server:2019-latest
    restart: on-failure

    environment:
      SA_PASSWORD: ${MSSQL_PASSWORD:-password_!23}
      ACCEPT_EULA: y
      MSSQL_TCP_PORT: 1433
    ports:
      - "11433:1433"
    networks:
      - jwc
    volumes:
      - jwc_mssql_test_data:/var/opt/mssql

networks:
  jwc:
    driver: bridge

volumes:
  jwc_mssql_data:
    driver: local
  jwc_mssql_test_data:
    driver: local
