pip install azure-common==1.1.27
pip install azure-core==1.13.0
pip install azure-identity==1.5.0
pip install azure-keyvault==4.1.0
pip install azure-keyvault-certificates==4.2.1
pip install azure-keyvault-keys==4.3.1
pip install azure-keyvault-secrets==4.2.0
pip install azure-storage-blob==12.8.0
pip install pandas==0.25.3
pip install numpy==1.13.3
pip install scikit-learn==0.22.1
pip install holidays
pip install dill
pip install adal
pip install joblib
pip install Babel