# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger: none

pool:
  vmImage: 'ubuntu-latest'

parameters:
  - name: 'AppServiceAuthSession'
    type: string
    default: 'AppServiceAuthSession'
  - name: 'AppServiceUrl'
    type: string
    default: 'AppServiceUrl'
variables:
  token: ${{ parameters.AppServiceAuthSession }}
  url: ${{ parameters.AppServiceUrl }}
stages:
  - stage: Carina_API_test
    pool:
      vmImage: 'ubuntu-latest'
    displayName: Running Carina API tests for ProjectStaffing
    jobs:
      - job: run_API_tests
        displayName: 'Running Carina API test'
        steps:
          - task: Bash@3
            displayName: 'Executing API tests'
            inputs:
              filePath: 'solutions/projectstaffing/api-tests/run_tests.sh'
              arguments: $(token) $(url)
              workingDirectory: 'solutions/projectstaffing/api-tests'
          - task: PublishPipelineArtifact@1
            inputs:
              targetPath: 'solutions/projectstaffing/api-tests/target'
              publishLocation: 'pipeline'
